In [2]:
!pip install psycopg

Collecting psycopg
  Downloading psycopg-3.3.4-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: tzdata in c:\users\chake\anaconda3\envs\ds_env_01\lib\site-packages (from psycopg) (2025.3)
Downloading psycopg-3.3.4-py3-none-any.whl (213 kB)
Installing collected packages: psycopg
Successfully installed psycopg-3.3.4

In [8]:
import psycopg
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

# Suppress warnings for cleaner output
warnings.filterwarnings("ignore")

conn_string = "postgresql://neondb_owner:npg_bJClhV9r5mqi@ep-icy-dawn-apa9ijea-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

conn = psycopg.connect(conn_string)
cur = conn.cursor()

In [9]:

sql = "SELECT * FROM feature_usage;"
df = pd.read_sql(sql, conn)
df.head()

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
0,U-1c6c24,S-0fcf7d,2023-07-27,feature_20,9,5004,0,False
1,U-f07cb8,S-c25263,2023-08-07,feature_5,9,369,0,False
2,U-096807,S-f29e7f,2023-12-07,feature_3,9,1458,0,False
3,U-6b1580,S-be655e,2024-07-28,feature_40,5,2085,0,False
4,U-720a29,S-f9b1d0,2024-12-02,feature_12,12,900,0,False

In [17]:
sql = """
SELECT usage_id, COUNT(*) as occurrences
FROM feature_usage
GROUP BY usage_id
HAVING COUNT(*) > 1
ORDER BY occurrences DESC
LIMIT 10
"""
occurence_list = []
cur.execute(sql)
for row in cur.fetchall():
    occurence = row[0]
    occurence_list.append(occurence)

occurence_list

['U-ae1a6c',
 'U-74b23f',
 'U-649cec',
 'U-2103bb',
 'U-7a87ed',
 'U-52f4ae',
 'U-b0ae95',
 'U-8128da',
 'U-7c6703',
 'U-48a4aa']

In [20]:
sql = f"""SELECT * FROM feature_usage
WHERE usage_id IN ({','.join([str(id) for id in occurence_list])})"""

df_occurrences = pd.read_sql(sql, conn)
df_occurrences.head()

DatabaseError: Execution failed on sql 'SELECT * FROM feature_usage
WHERE usage_id IN (U-ae1a6c,U-74b23f,U-649cec,U-2103bb,U-7a87ed,U-52f4ae,U-b0ae95,U-8128da,U-7c6703,U-48a4aa)': trailing junk after numeric literal at or near "74b23f"
LINE 2: WHERE usage_id IN (U-ae1a6c,U-74b23f,U-649cec,U-2103bb,U-7a8...
                                      ^

In [23]:
quoted_ids = ",".join(f"'{uid}'" for uid in occurence_list)
sql = f"""
SELECT *
FROM feature_usage
WHERE usage_id IN ({quoted_ids})
ORDER BY usage_id
"""
print(sql)
df_occurrences = pd.read_sql(sql, conn)
df_occurrences.head(20)

SELECT *
FROM feature_usage
WHERE usage_id IN ('U-ae1a6c','U-74b23f','U-649cec','U-2103bb','U-7a87ed','U-52f4ae','U-b0ae95','U-8128da','U-7c6703','U-48a4aa')
ORDER BY usage_id

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
0,U-2103bb,S-7fc49b,2023-04-18,feature_12,9,5022,1,False
1,U-2103bb,S-ae3270,2024-01-06,feature_3,10,5510,0,False
2,U-48a4aa,S-383ac2,2023-02-12,feature_28,14,7126,0,False
3,U-48a4aa,S-93f835,2024-08-24,feature_39,10,4770,0,False
4,U-52f4ae,S-0756ce,2024-03-30,feature_6,6,2178,1,False
5,U-52f4ae,S-444f22,2024-10-05,feature_6,9,3348,2,False
6,U-649cec,S-2971ae,2023-07-07,feature_36,5,1165,0,False
7,U-649cec,S-d54349,2024-12-25,feature_33,12,3456,2,False
8,U-74b23f,S-51b3ed,2023-10-17,feature_33,9,4824,1,False
9,U-74b23f,S-da9362,2024-03-23,feature_22,6,2118,0,False
10,U-7a87ed,S-f1aa04,2023-07-10,feature_13,9,333,0,False
11,U-7a87ed,S-3803ff,2024-04-05,feature_2,14,5516,0,False
12,U-7c6703,S-ae9ce7,2024-12-21,feature_40,13,897,0,False
13,U-7c6703,S-124207,2023-11-30,feature_32,7,483,0,False
14,U-8128da,S-6c969d,2024-05-27,feature_34,9,2520,0,False
15,U-8128da,S-9c85b0,2023-04-21,feature_24,13,806,1,False
16,U-ae1a6c,S-d6aefa,2024-07-04,feature_26,13,4680,0,False
17,U-ae1a6c,S-55db9e,2024-12-24,feature_17,12,420,2,False
18,U-b0ae95,S-21f8b3,2023-10-15,feature_5,12,5568,0,False
19,U-b0ae95,S-1082f7,2024-06-09,feature_36,4,1440,0,False